import type { Metadata } from "next";
import {  Work_Sans} from "next/font/google";
import "../globals.css";
import DashboardWrapper from "@/app/DashboardWrapper";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable}  antialiased`}
      >
       <DashboardWrapper>{children}</DashboardWrapper>   
      </body>
    </html>
  );
}
